# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-11 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_name', models.CharField(max_length=255, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435')),
                ('city', models.TextField(verbose_name='\u0433\u043e\u0440\u043e\u0434')),
                ('street_home', models.TextField(verbose_name='\u0443\u043b\u0438\u0446\u0430_\u0434\u043e\u043c')),
                ('tel', models.TextField(verbose_name='\u0442\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('main_descr', models.TextField(verbose_name='\u0433\u043b\u0430\u0432\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442')),
            ],
            options={
                'verbose_name': '\u043e\u0431\u0449\u0438\u0435 \u0434\u0430\u043d\u043d\u044b\u0435',
                'verbose_name_plural': '\u043e\u0431\u0449\u0438\u0435 \u0434\u0430\u043d\u043d\u044b\u0435',
            },
        ),
    ]
