# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-07 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_name', models.CharField(max_length=255, verbose_name='название на главной странице')),
                ('city', models.TextField(verbose_name='город')),
                ('street_home', models.TextField(verbose_name='улица_дом')),
                ('tel', models.TextField(verbose_name='телефон')),
                ('main_descr', models.TextField(verbose_name='главный текст')),
            ],
            options={
                'verbose_name_plural': 'общие данные',
                'verbose_name': 'общие данные',
            },
        ),
    ]
