# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-11 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': '\u0410\u043b\u044c\u0431\u043e\u043c',
                'verbose_name_plural': '\u0410\u043b\u044c\u0431\u043e\u043c\u044b',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('order', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438',
                'verbose_name_plural': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('descr', models.TextField(blank=True, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('img', easy_thumbnails.fields.ThumbnailerImageField(upload_to=b'', verbose_name='\u0444\u043e\u0442\u043e')),
                ('album_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Album', verbose_name='\u0430\u043b\u044c\u0431\u043e\u043c')),
            ],
            options={
                'verbose_name': '\u0444\u043e\u0442\u043e',
                'verbose_name_plural': '\u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='preview',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Photo'),
        ),
        migrations.AddField(
            model_name='album',
            name='preview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Photo'),
        ),
    ]
