# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-10 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('descr', models.TextField(blank=True, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('img', models.ImageField(upload_to=b'', verbose_name='\u0444\u043e\u0442\u043e')),
                ('album_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Album', verbose_name='\u0430\u043b\u044c\u0431\u043e\u043c')),
            ],
            options={
                'verbose_name': '\u0444\u043e\u0442\u043e',
                'verbose_name_plural': '\u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='preview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Photo'),
        ),
    ]
