# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-12 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170211_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('order', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Альбом',
                'ordering': ['order'],
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='news',
            name='preview',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Photo'),
        ),
    ]
