# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-26 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170212_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['order'], 'verbose_name': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438', 'verbose_name_plural': '\u041d\u043e\u0432\u043e\u0441\u0442\u0438'},
        ),
        migrations.AlterField(
            model_name='album',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=b'', verbose_name='\u0444\u043e\u0442\u043e'),
        ),
    ]
