# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170226_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, help_text='\u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440, uslugi', verbose_name='URL \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, help_text='\u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440, uslugi', verbose_name='URL \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b'),
        ),
    ]
