# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170323_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='desctiption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='desctiption',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
